-- FUNÇÕES
CREATE OR REPLACE FUNCTION FC_FATURAMENTO
RETURN FLOAT

AS
    V_FATURAMENTO FLOAT;

BEGIN 
    SELECT 
        SUM(QUANTIDADE * VALOR_UNIT)
        INTO V_FATURAMENTO
    FROM 
        VENDAS;
    RETURN V_FATURAMENTO;
END;