-- PROCEDURE
CREATE OR REPLACE PROCEDURE STP_INSERT_VENDAS (
    P_NOTAFISCAL VENDAS.NOTAFISCAL%TYPE,
    P_IDPRO VENDAS.IDPRO%TYPE,
    P_VENDEDOR VENDAS.VENDEDOR%TYPE,
    P_SUPERVISOR VENDAS.SUPERVISOR%TYPE,
    P_QUANTIDADE VENDAS.QUANTIDADE%TYPE
)

AS 

BEGIN 
    INSERT INTO VENDAS (
        DTVENDA, 
        NOTAFISCAL, 
        IDPRO, 
        VENDEDOR, 
        SUPERVISOR, 
        QUANTIDADE, 
        VALOR_UNIT
    )
    VALUES (
        SYSDATE, 
        P_NOTAFISCAL, 
        P_IDPRO, 
        P_VENDEDOR, 
        P_SUPERVISOR, 
        P_QUANTIDADE, 
        (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = P_IDPRO)
    );

END;





