-- FAZENDO UM SELECT ROCHEDO

--COUT - MOSTRA QUANTIDADE DE PRODUTOS NA TABELA
SELECT COUNT(*) FROM PRODUTOS;

--GROUP BY - MOSTRAR CONTAGEM DOS PRODUTOS AGRUPADOS POR LINHA_PROD - USADO EM CONJUNTO COM OUTROS COMANDOS
SELECT LINHA_PROD, COUNT(*) 
FROM PRODUTOS
GROUP BY LINHA_PROD;

-- MAX, WHERE E SUBSELECT
SELECT PRODUTO, CUSTO_UNITARIO
FROM PRODUTOS
WHERE CUSTO_UNITARIO IN (SELECT MAX(CUSTO_UNITARIO) FROM PRODUTOS);