--CRIANDO TABELA DE VENDAS
CREATE TABLE VENDAS (
    DTVENDA DATE,
    NOTAFISCAL NUMBER,
    IDPRO INT,
    VENDEDOR VARCHAR2(20),
    SUPERVISOR VARCHAR2(20),
    QUANTIDADE NUMBER,
    VALOR_UNIT FLOAT
);

-- criando relacionamento entre vendas e produtos
-- não pode ser possivel vender um produto que n esteja na tablea de produtos

ALTER TABLE VENDAS ADD CONSTRAINT FK_VENDAS_PRODUTOS FOREIGN KEY (IDPRO) REFERENCES  PRODUTOS (IDPRO);

--INSERINDO NOVA VENDA NA TABELA DE VENDAS
INSERT INTO VENDAS
    (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
VALUES
    (SYSDATE, 123, 1, 'MARIA', 'JOSE', 10, 5.09);
    
-- SÓ DE FAZER O RELACIONAMENTO, A TABELA N ACEITA UM DADO QUE A FOREIGN KEY N EXISTA NA TABELA DE PRODUTOS


/*
 -- VENDEDORES X SUPERVISORES
    1 EQUIPE
    MARIA RIBEIRO  - ROBERTO SILVA
    JOSE RODRIGUES - ROBERTO SILVA
    ALONSO PEREIRA - ROBERTO SILVA
    
    LIVIA ASSUNÇÃO - ALBERTO VIEIRA
    NAYARA BORGES  - ALBERTO VIEIRA
    RENATO NEVES   - ALBERTO VIEIRA
*/


-- populando tabela de vendas com insert e select para adicionar
-- porcentagem de lucro no custo unitario

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE+1, 2222, 16, 'NAYARA BORGES', 'ALBERTO VIEIRA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 16));

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE-1, 2223, 3, 'NAYARA BORGES', 'ALBERTO VIEIRA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 3));

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE+2, 2224, 13, 'NAYARA BORGES', 'ALBERTO VIEIRA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 13));

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE-3, 2225, 5, 'RENATO NEVES', 'ALBERTO VIEIRA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 5));

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE-4, 2226, 6, 'RENATO NEVES', 'ALBERTO VIEIRA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 6));

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE-5, 2227, 7, 'ALONSO PEREIRA', 'ROBERTO SILVA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 7));

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE-6, 2228, 8, 'ALONSO PEREIRA', 'ROBERTO SILVA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 8));

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE-9, 2229, 6, 'ALONSO PEREIRA', 'ROBERTO SILVA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 6));

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE-9, 2230, 18, 'LIVIA ASSUNÇÃO', 'ALBERTO VIEIRA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 18));

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE-8, 2231, 9, 'LIVIA ASSUNÇÃO', 'ALBERTO VIEIRA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 9));

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE-7, 2232, 14, 'LIVIA ASSUNÇÃO', 'ALBERTO VIEIRA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 14));

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE-6, 3336, 3, 'LIVIA ASSUNÇÃO', 'ALBERTO VIEIRA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 3));

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE-6, 3336, 4, 'LIVIA ASSUNÇÃO', 'ALBERTO VIEIRA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 4));

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE-6, 3336, 2, 'JOSE RODRIGUES', 'ROBERTO SILVA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 2));

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE-6, 3336, 1, 'JOSE RODRIGUES', 'ROBERTO SILVA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 1));

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE-5, 3336, 17, 'LIVIA ASSUNÇÃO', 'ALBERTO VIEIRA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 17));

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE-5, 1598, 17, 'NAYARA BORGES', 'ALBERTO VIEIRA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 17));

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE-5, 10058, 17, 'RENATO NEVES', 'ALBERTO VIEIRA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 17));

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE-4, 9998, 17, 'ALONSO PEREIRA', 'ROBERTO SILVA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 17));

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE-3, 9998, 18, 'ALONSO PEREIRA', 'ROBERTO SILVA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 18));

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE-5, 9998, 4, 'ALONSO PEREIRA', 'ROBERTO SILVA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 4));

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE-5, 5252, 17, 'JOSE RODRIGUES', 'ROBERTO SILVA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 17));

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE-7, 5252, 18, 'JOSE RODRIGUES', 'ROBERTO SILVA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 18));

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE-8, 5252, 10, 'JOSE RODRIGUES', 'ROBERTO SILVA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 10));

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE-1, 1234, 17, 'MARIA RIBEIRO', 'ROBERTO SILVA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 17));

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE-2, 1234, 18, 'MARIA RIBEIRO', 'ROBERTO SILVA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 18));

INSERT INTO VENDAS (DTVENDA, NOTAFISCAL, IDPRO, VENDEDOR, SUPERVISOR, QUANTIDADE, VALOR_UNIT)
            VALUES (SYSDATE-3, 1234, 11, 'MARIA RIBEIRO', 'ROBERTO SILVA', 3, 
                   (SELECT CUSTO_UNITARIO + (CUSTO_UNITARIO * 30)/100 FROM PRODUTOS WHERE IDPRO = 11));
                   
SELECT * FROM VENDAS
WHERE VENDEDOR = 'MARIA';


-- UTILIZANDO A PROCEDURE STP_INSERT_VENDAS PARA ADICIONAR DADOS NA TABELA VENDAS
EXEC STP_INSERT_VENDAS (55568, 12, 'MARIA', 'JOSE', 10);

-- UTILIZANDO FUNÇÃO PARA RETORNAR TOTAL DE VENDAS
SELECT ROUND(FC_FATURAMENTO(), 2) AS FATURAMENTO_TOTAL FROM DUAL;
