-- usando o update e delete
SELECT * 
FROM VENDAS
WHERE NOTAFISCAL = 5252;

UPDATE VENDAS
SET VALOR_UNIT = 15
WHERE NOTAFISCAL = 5252
AND IDPRO = 18;

DELETE FROM VENDAS
WHERE NOTAFISCAL = 5252
AND IDPRO = 10;