-- CRIANDO UMA VIEW
CREATE OR REPLACE VIEW VW_FATURAMENTO_TOTAL
AS

SELECT
    TO_CHAR (VEN.DTVENDA, 'MM') AS MES_VENDA,
    'NF-E: ' || VEN.NOTAFISCAL AS NFe,
    VEN.IDPRO,
    PRO.PRODUTO,
    VEN.VENDEDOR,
    VEN.SUPERVISOR,
    VEN.QUANTIDADE,
    VEN.VALOR_UNIT,
    TO_CHAR ((VEN.QUANTIDADE * VEN.VALOR_UNIT), '999990D99') || 'R$' AS VALOR_TOTAL,
    TO_CHAR ((VEN.QUANTIDADE * PRO.CUSTO_UNITARIO), '999990D99') || 'R$' AS CUSTO,
    TO_CHAR (((VEN.QUANTIDADE * VEN.VALOR_UNIT) - (VEN.QUANTIDADE * PRO.CUSTO_UNITARIO)), '999990D99') || 'R$' AS LUCRO
FROM VENDAS VEN, PRODUTOS PRO
WHERE VEN.IDPRO = PRO.IDPRO;

SELECT * FROM vw_faturamento_total;
